Port = {{cfg.port}}

[database]
Name = "{{cfg.database.name}}"
{{#if bind.database ~}}
Host = "{{bind.database.first.sys.ip}}"
Port = {{bind.database.first.cfg.driver-port}}
{{else ~}}
Host = "{{cfg.database.host}}"
Port = {{cfg.database.port}}
{{/if ~}}
